//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class donat
    {
        public int numb_donat { get; set; }
        public System.DateTime date_donat { get; set; }
        public decimal summ { get; set; }
        public int numb_pay { get; set; }
        public string loginn { get; set; }
        public Nullable<decimal> inn_fund { get; set; }
    
        public virtual user1 user1 { get; set; }
        public virtual pay_type pay_type { get; set; }
        public virtual funds funds1 { get; set; }
    }
}
