//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry1
    {
        public int numb_entry { get; set; }
        public System.DateTime date_entry { get; set; }
        public string loginn { get; set; }
        public int numb_event { get; set; }
    
        public virtual user1 user1 { get; set; }
        public virtual event12 event12 { get; set; }
    }
}
