//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pay_type()
        {
            this.donat = new HashSet<donat>();
        }
    
        public int numb_pay { get; set; }
        public decimal numb_card { get; set; }
        public bool google_pay { get; set; }
        public bool pay_pal { get; set; }
        public bool qiwi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donat> donat { get; set; }
    }
}
