//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user1()
        {
            this.donat = new HashSet<donat>();
            this.entry1 = new HashSet<entry1>();
        }
    
        public string loginn { get; set; }
        public string surname { get; set; }
        public string namee { get; set; }
        public string patronymic { get; set; }
        public decimal phone_user { get; set; }
        public string email { get; set; }
        public string passwordd { get; set; }
        public string leader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donat> donat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entry1> entry1 { get; set; }
    }
}
